<?php
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TvSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvSeriesRepository extends EntityRepository
{
    /**
     * Get the paginated list of series
     *
     * @param int $page
     * @param int $maxperpage
     * @param string $sortby
     * @return Paginator
     */
    public function findForPagination($page=1, $maxperpage=10)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('series')
            ->from('AppBundle:TvSeries','series')
            ->orderBy('series.name', 'ASC')
        ;

        $qb->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($qb);
    }

    public function getCount()
    {
        $qb = $this->createQueryBuilder('series')
            ->select('COUNT(series)')
            ->getQuery()
            ->getSingleScalarResult();

        return $qb;
    }
}