<?php
namespace AppBundle\Repository;
/**
 * TvSerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvSeriesRepository extends \Doctrine\ORM\EntityRepository
{
}